name: 'Delete Package Versions'
description: 'Finds and deletes package version'
inputs:
  name:
    description: 'A regular expression that is matched against the name of the package'
    required: true
  version:
    description: 'A regular expression that is matched against the name of the version'
    required: true
  type:
    description: 'The package type. For instance, npm or maven'
    required: true
  tag:
    description: 'A regular expression that is matched against the version tag'
    required: false
  untagged:
    description: 'Delete untagged versions'
    required: false
    default: "false"
  token:
    description: 'Token with the necessary scopes to read package versions.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
